<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Prism.Unity" />
    <PackageReference Include="System.Private.Uri" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\WpfCustomControlLibrary\WpfCustomControlLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dialogs\DetailCoverDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
