// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class Costunit
{
    public int CostunitId { get; set; }

    public string? Description { get; set; }

    public bool Locked { get; set; }

    public bool Invalid { get; set; }

    public virtual ICollection<AccountCost> AccountCosts { get; set; } = new List<AccountCost>();

    public virtual ICollection<ProxyOrder> ProxyOrders { get; set; } = new List<ProxyOrder>();

    public virtual ICollection<RessourceCostUnit> RessourceCostUnits { get; set; } = new List<RessourceCostUnit>();

    public virtual ICollection<WorkSap> WorkSaps { get; set; } = new List<WorkSap>();
}