// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using El2Core.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace El2Core.Models
{
    public partial class DB_COS_LIEFERLISTE_SQLContext
    {
        private IDB_COS_LIEFERLISTE_SQLContextProcedures? _procedures;

        public virtual IDB_COS_LIEFERLISTE_SQLContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new DB_COS_LIEFERLISTE_SQLContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IDB_COS_LIEFERLISTE_SQLContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class DB_COS_LIEFERLISTE_SQLContextProcedures : IDB_COS_LIEFERLISTE_SQLContextProcedures
    {
        private readonly DB_COS_LIEFERLISTE_SQLContext _context;

        public DB_COS_LIEFERLISTE_SQLContextProcedures(DB_COS_LIEFERLISTE_SQLContext context)
        {
            _context = context;
        }

        public virtual async Task<List<ProductMaterialsResult>?> ProductMaterialsAsync(string? usrID, OutputParameter<int>? returnValue = null, CancellationToken? cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "usrID",
                    Size = 20,
                    Value = usrID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<ProductMaterialsResult>("EXEC @returnValue = [dbo].[ProductMaterials] @usrID = @usrID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
