// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using El2Core.Models;

namespace El2Core.Models
{
    public partial class DB_COS_LIEFERLISTE_SQLContext
    {

        [DbFunction("ProductMaterialFunc", "dbo")]
        public IQueryable<ProductMaterialFuncResult> ProductMaterialFunc(string userId)
        {
            return FromExpression(() => ProductMaterialFunc(userId));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProductMaterialFuncResult>().HasNoKey();
        }
    }
}
