// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace El2Core.Models
{
    public partial class ProductMaterialsResult
    {
        [StringLength(255)]
        public string TTNR { get; set; } = default!;
        [StringLength(256)]
        public string? Bezeichng { get; set; }
        [StringLength(50)]
        public string AID { get; set; } = default!;
        public DateTime? Eckstart { get; set; }
        public DateTime? Eckende { get; set; }
        public DateTime? timestamp { get; set; }
        [StringLength(255)]
        public string? DummyMat { get; set; }
        [StringLength(50)]
        public string? ProID { get; set; }
        public DateTime? Iststart { get; set; }
        public DateTime? Istende { get; set; }
        [StringLength(255)]
        public string? LieferTermin { get; set; }
        public bool abgeschlossen { get; set; }
        public bool fertig { get; set; }
        [StringLength(255)]
        public string? Bemerkung { get; set; }
        [StringLength(255)]
        public string? SysStatus { get; set; }
        public int? Quantity { get; set; }
        public DateTime? CompleteDate { get; set; }
        public int ArchivState { get; set; }
        [StringLength(150)]
        public string? ArchivPath { get; set; }
        public short VNR { get; set; }
        [Column("Quantity-scrap")]
        public int? Quantityscrap { get; set; }
        [Column("Quantity-yield")]
        public int? Quantityyield { get; set; }
        [Column("Quantity-miss")]
        public int? Quantitymiss { get; set; }
        [Column("Quantity-rework")]
        public int? Quantityrework { get; set; }
        [Column("MSF-InWork")]
        public bool MSFInWork { get; set; }
        [StringLength(50)]
        public string? MSF { get; set; }
        public int? CostID { get; set; }
    }
}
