// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace El2Core.Models
{
    public partial class ProductMaterialsResult
    {
        [StringLength(255)]
        public string TTNR { get; set; } = default!;
        [StringLength(256)]
        public string? Bezeichng { get; set; }
        [StringLength(50)]
        public string AID { get; set; } = default!;
        public DateTime? Eckstart { get; set; }
        public DateTime? Eckende { get; set; }
        public DateTime? timestamp { get; set; }
        [StringLength(10)]
        public string? AuftragFarbe { get; set; }
        [StringLength(255)]
        public string? DummyMat { get; set; }
        [StringLength(50)]
        public string? ProID { get; set; }
        public DateTime? Iststart { get; set; }
        public DateTime? Istende { get; set; }
        [StringLength(255)]
        public string? LieferTermin { get; set; }
        public bool abgeschlossen { get; set; }
        [StringLength(255)]
        public string? Prio { get; set; }
        public bool fertig { get; set; }
        public bool Dringend { get; set; }
        [StringLength(255)]
        public string? Bemerkung { get; set; }
        [StringLength(255)]
        public string? SysStatus { get; set; }
        [StringLength(255)]
        public string? MarkCode { get; set; }
        public short VNR { get; set; }
        [StringLength(255)]
        public string? ArbPlSAP { get; set; }
        [StringLength(150)]
        public string? Text { get; set; }
        public DateTime? SpaetStart { get; set; }
        public DateTime? SpaetEnd { get; set; }
        public float? BEAZE { get; set; }
        public float? RSTZE { get; set; }
        public float? WRTZE { get; set; }
        [StringLength(255)]
        public string? VrgSysStatus { get; set; }
        public DateTime? Termin { get; set; }
        [StringLength(2147483647)]
        public string? Bem_M { get; set; }
        [StringLength(2147483647)]
        public string? Bem_T { get; set; }
        [StringLength(2147483647)]
        public string? Bem_MA { get; set; }
        public bool aktuell { get; set; }
        [Column("Quantity-scrap")]
        public int? Quantityscrap { get; set; }
        [Column("Quantity-yield")]
        public int? Quantityyield { get; set; }
        [Column("Quantity-miss")]
        public int? Quantitymiss { get; set; }
        [Column("Quantity-rework")]
        public int? Quantityrework { get; set; }
        public float? ProcessTime { get; set; }
        public DateTime? ActualStartDate { get; set; }
        public DateTime? ActualEndDate { get; set; }
        public int? RID { get; set; }
        [StringLength(2147483647)]
        public string? CommentMach { get; set; }
        [Column("MSF-InWork")]
        public bool MSFInWork { get; set; }
        [StringLength(50)]
        public string? MSF { get; set; }
        public int? CostID { get; set; }
    }
}
