// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ProxyOrder
{
    public long OrderId { get; set; }

    public string? RbId { get; set; }

    public int? CostId { get; set; }

    public string AccId { get; set; } = null!;

    public int? Quantity { get; set; }

    public string? CommentText { get; set; }

    public DateTime? Created { get; set; }

    public string? ProjId { get; set; }

    public virtual IdmAccount Acc { get; set; } = null!;

    public virtual Costunit? Cost { get; set; }

    public virtual ICollection<EmployeeNote> EmployeeNotes { get; set; } = new List<EmployeeNote>();

    public virtual Project? Proj { get; set; }

    public virtual OrderRb? Rb { get; set; }
}