// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace El2Core.Models;

public partial class ViewVorgangClosedDate
{
    public string VorgangId { get; set; } = null!;

    public string Aid { get; set; } = null!;

    public short Vnr { get; set; }

    public string? ArbPlSap { get; set; }

    public string? Text { get; set; }

    public DateTime? SpaetStart { get; set; }

    public DateTime? SpaetEnd { get; set; }

    public float? Beaze { get; set; }

    public float? Rstze { get; set; }

    public float? Wrtze { get; set; }

    public string? BeazeEinheit { get; set; }

    public string? RstzeEinheit { get; set; }

    public string? WrtzeEinheit { get; set; }

    public string? SysStatus { get; set; }

    public string? SteuSchl { get; set; }

    public string? BasisMg { get; set; }

    public DateTime? Termin { get; set; }

    public string? BemM { get; set; }

    public string? BemT { get; set; }

    public string? BemMa { get; set; }

    public bool Aktuell { get; set; }

    public int? QuantityScrap { get; set; }

    public int? QuantityYield { get; set; }

    public int? QuantityMiss { get; set; }

    public string? ProcessingUom { get; set; }

    public float? ProcessTime { get; set; }

    public int? QuantityRework { get; set; }

    public bool Visability { get; set; }

    public DateTime? ActualStartDate { get; set; }

    public DateTime? ActualEndDate { get; set; }

    public string? Bullet { get; set; }

    public int? Spos { get; set; }

    public int? Rid { get; set; }

    public string? CommentMach { get; set; }

    public string? BulletTwo { get; set; }

    public string? MarkCode { get; set; }

    public DateTime? KlimaPrint { get; set; }

    public float? Correction { get; set; }

    public int? QuantityMissNeo { get; set; }

    public string? SortPos { get; set; }

    public bool MsfInWork { get; set; }

    public string? Msf { get; set; }

    public string? Mattext { get; set; }

    public DateTime? Eckstart { get; set; }

    public DateTime? Eckende { get; set; }

    public DateTime? Timestamp { get; set; }

    public string? AuftragFarbe { get; set; }

    public string? Material { get; set; }

    public string? DummyMat { get; set; }

    public string? ProId { get; set; }

    public DateTime? Iststart { get; set; }

    public DateTime? Istende { get; set; }

    public string? LieferTermin { get; set; }

    public bool Abgeschlossen { get; set; }

    public string? Prio { get; set; }

    public bool Fertig { get; set; }

    public bool Dringend { get; set; }

    public string? Bemerkung { get; set; }

    public string? OrderRbSysstatus { get; set; }

    public string? OrderRbMarkCode { get; set; }

    public bool Ausgebl { get; set; }

    public bool Mappe { get; set; }

    public int? Quantity { get; set; }

    public string? Wbselement { get; set; }

    public DateTime? CompleteDate { get; set; }

    public bool Archivated { get; set; }

    public int ArchivState { get; set; }

    public string? ArchivPath { get; set; }

    public string? Bezeichng { get; set; }

    public string? Type { get; set; }
}