// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using El2Core.ViewModelBase;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace El2Core.Models;

public partial class Vorgang : ModelBase
{
    [NotMapped]
    public bool? Alert { get; set; }
    [NotMapped]
    public string? Extends { get; set; }
    [NotMapped]
    public string? Formula { get; set; }
    [NotMapped]
    public int AttCount { get; set; }
    public string VorgangId { get; set; } = null!;

    public string Aid { get; set; } = null!;

    public short Vnr { get; set; }

    public string? ArbPlSap { get; set; }

    public string? Text { get; set; }

    public DateTime? SpaetStart { get; set; }

    public DateTime? SpaetEnd { get; set; }

    public float? Beaze { get; set; }

    public float? Rstze { get; set; }

    public float? Wrtze { get; set; }

    public string? BeazeEinheit { get; set; }

    public string? RstzeEinheit { get; set; }

    public string? WrtzeEinheit { get; set; }

    public string? SysStatus { get; set; }

    public string? SteuSchl { get; set; }

    public string? BasisMg { get; set; }

    public DateTime? Termin { get; set; }

    public string? BemM { get; set; }

    public string? BemT { get; set; }

    public string? BemMa { get; set; }

    public bool Aktuell { get; set; }

    public int? QuantityScrap { get; set; }

    public int? QuantityYield { get; set; }

    public int? QuantityMiss { get; set; }

    public string? ProcessingUom { get; set; }

    public float? ProcessTime { get; set; }

    public int? QuantityRework { get; set; }

    public bool Visability { get; set; }

    public DateTime? ActualStartDate { get; set; }

    public DateTime? ActualEndDate { get; set; }

    public string? Bullet { get; set; }

    public int? Spos { get; set; }

    public int? Rid { get; set; }

    public string? CommentMach { get; set; }

    public string? BulletTwo { get; set; }

    public string? MarkCode { get; set; }

    public DateTime? KlimaPrint { get; set; }

    public float? Correction { get; set; }

    public int? QuantityMissNeo { get; set; }

    public string? SortPos { get; set; }

    public bool MsfInWork { get; set; }

    public string? Msf { get; set; }

    public bool Prepare { get; set; }

    public virtual OrderRb AidNavigation { get; set; } = null!;

    public virtual WorkSap? ArbPlSapNavigation { get; set; }

    public virtual ICollection<EmployeeNote> EmployeeNotes { get; set; } = new List<EmployeeNote>();

    public virtual ICollection<MeasureRessVorgang> MeasureRessVorgangs { get; set; } = new List<MeasureRessVorgang>();

    public virtual ICollection<Response> Responses { get; set; } = new List<Response>();

    public virtual Ressource? RidNavigation { get; set; }

    public virtual ICollection<VorgangAttachment> VorgangAttachments { get; set; } = new List<VorgangAttachment>();

    public virtual VorgangDocu? VorgangDocu { get; set; }
}