<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="Microsoft.Office.Core">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>8</VersionMinor>
      <VersionMajor>2</VersionMajor>
      <Guid>2df8d04c-5bfa-101b-bde5-00aa0044de52</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
    <COMReference Include="Microsoft.Office.Interop.Word">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>7</VersionMinor>
      <VersionMajor>8</VersionMajor>
      <Guid>00020905-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetKit.Wpf.AutoCompleteComboBox" />
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="OpenXmlPowerTools" />
    <PackageReference Include="Prism.Unity" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Private.Uri" />
    <PackageReference Include="System.Text.RegularExpressions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\WpfCustomControlLibrary\WpfCustomControlLibrary.csproj" />
  </ItemGroup>

</Project>
