<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <NeutralLanguage>de-AT</NeutralLanguage>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Users\scm2hl\Documents\Certificates\Lieferliste_WPF_TemporaryKey.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Prism.Unity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompositeCommands.Core\CompositeCommands.Core.csproj" />
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\WpfCustomControlLibrary\WpfCustomControlLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\FlowDocumentViewer.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UserControls\LieferlisteControl.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

</Project>
