<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Prism.Unity" />
    <PackageReference Include="System.Private.Uri" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompositeCommands.Core\CompositeCommands.Core.csproj" />
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\vhCalendar\vhCalendar.csproj" />
    <ProjectReference Include="..\WpfCustomControlLibrary\WpfCustomControlLibrary.csproj" />
  </ItemGroup>

</Project>
