<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ReportTypes\**" />
    <EmbeddedResource Remove="ReportTypes\**" />
    <None Remove="ReportTypes\**" />
    <Page Remove="ReportTypes\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" NoWarn="NU1701" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Prism.Core" />
    <PackageReference Include="Prism.Unity" />
    <PackageReference Include="System.Private.Uri" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompositeCommands.Core\CompositeCommands.Core.csproj" />
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\vhCalendar\vhCalendar.csproj" />
  </ItemGroup>

</Project>
