<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
	  <WindowsSdkPackageVersion>10.0.19041.54</WindowsSdkPackageVersion>
    <LangVersion>Latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <NeutralLanguage>de-AT</NeutralLanguage>
    <ApplicationIcon>el4-application.ico</ApplicationIcon>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\Users\scm2hl\Documents\Certificates\Lieferliste_WPF_TemporaryKey.pfx</AssemblyOriginatorKeyFile>
    <Configuration>
      <configSections>
        <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
      </configSections>
    </Configuration>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>full</DebugType>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <WarningLevel>3</WarningLevel>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\**" />
    <EmbeddedResource Remove="Data\**" />
    <None Remove="Data\**" />
    <Page Remove="Data\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Planning\ParkMachine.cs" />
    <Compile Remove="Planning\ParkMachineFactory.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="CodeMetricsConfig.txt" />
    <None Remove="flowdocumenttoxhtml.xslt" />
    <None Remove="Images\1602309.png" />
    <None Remove="Images\3160908.png" />
    <None Remove="Images\AboutLogo.png" />
    <None Remove="Images\add-group.png" />
    <None Remove="Images\add-user.png" />
    <None Remove="Images\book.png" />
    <None Remove="Images\BOSCH2.jpg" />
    <None Remove="Images\Bosch_Anker-Transparent.png" />
    <None Remove="Images\Bosch_Anker.jpg" />
    <None Remove="Images\Bosch_Anker48.png" />
    <None Remove="Images\check128.png" />
    <None Remove="Images\check32.png" />
    <None Remove="Images\CircleFull128.png" />
    <None Remove="Images\CircleFull32.png" />
    <None Remove="Images\CircleRound128.png" />
    <None Remove="Images\CircleRound32.png" />
    <None Remove="Images\collapse.png" />
    <None Remove="Images\copy.png" />
    <None Remove="Images\copy16.png" />
    <None Remove="Images\cut-content-button.png" />
    <None Remove="Images\Database32.png" />
    <None Remove="Images\Database64.png" />
    <None Remove="Images\DB_Y.png" />
    <None Remove="Images\DB_Y32.png" />
    <None Remove="Images\delete.jpg" />
    <None Remove="Images\drill.png" />
    <None Remove="Images\edit.png" />
    <None Remove="Images\eraser.png" />
    <None Remove="Images\files-and-folders.png" />
    <None Remove="Images\format_text_bold.png" />
    <None Remove="Images\format_text_italic.png" />
    <None Remove="Images\format_text_underline.png" />
    <None Remove="Images\group.png" />
    <None Remove="Images\hide.png" />
    <None Remove="Images\left32.png" />
    <None Remove="Images\machine-color.png" />
    <None Remove="Images\machine.png" />
    <None Remove="Images\man.png" />
    <None Remove="Images\milling-machine.png" />
    <None Remove="Images\minus128.png" />
    <None Remove="Images\minus32.png" />
    <None Remove="Images\multiply-1.png" />
    <None Remove="Images\OrangeCross32.png" />
    <None Remove="Images\parking.png" />
    <None Remove="Images\paste-from-clipboard.png" />
    <None Remove="Images\paste.png" />
    <None Remove="Images\paste16.png" />
    <None Remove="Images\plan-edit.png" />
    <None Remove="Images\plan.png" />
    <None Remove="Images\planning.png" />
    <None Remove="Images\plus128.png" />
    <None Remove="Images\plus32.png" />
    <None Remove="Images\print.png" />
    <None Remove="Images\print1.png" />
    <None Remove="Images\refresh.png" />
    <None Remove="Images\right32.png" />
    <None Remove="Images\sort%282%29.png" />
    <None Remove="Images\sort-by-attributes-Asc16 %282%29.png" />
    <None Remove="Images\sort-by-attributes-Asc16.png" />
    <None Remove="Images\sort-by-attributes-Desc16 %282%29.png" />
    <None Remove="Images\sort-by-attributes-Desc16.png" />
    <None Remove="Images\sort-by-attributes-interface-button-option.png" />
    <None Remove="Images\sort-by-attributes.png" />
    <None Remove="Images\spacing.png" />
    <None Remove="Images\SplashPic.png" />
    <None Remove="Images\TooltipEmpl.png" />
    <None Remove="Images\unknown-file.png" />
    <None Remove="Images\user-edit.png" />
    <None Remove="Images\user-profiles %281%29.png" />
    <None Remove="Images\user-profiles.png" />
    <None Remove="Images\waste.jpg" />
    <None Remove="Images\waste2.jpg" />
    <None Remove="Log4Net.config" />
    <None Remove="VersionAutoIncrementer.tt" />
    <None Remove="VersionAutoIncrementer.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="el4-application.ico" />
    <Content Include="Log4Net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotNetKit.Wpf.AutoCompleteComboBox" />
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Text.RegularExpressions" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dialogs\ProcessTimeDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UserControls\CommentUserControl.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompositeCommands.Core\CompositeCommands.Core.csproj" />
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\ModuleDeliverList\ModuleDeliverList.csproj" />
    <ProjectReference Include="..\ModuleMeasuring\ModuleMeasuring.csproj" />
    <ProjectReference Include="..\ModulePlanning\ModulePlanning.csproj" />
    <ProjectReference Include="..\ModuleProducts\ModuleProducts.csproj" />
    <ProjectReference Include="..\ModuleProxyOrder\ModuleProxyOrder.csproj" />
    <ProjectReference Include="..\ModuleReport\ModuleReport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="flowdocumenttoxhtml.xslt" />
    <Resource Include="Images\1602309.png" />
    <Resource Include="Images\3160908.png" />
    <Resource Include="Images\AboutLogo.png" />
    <Resource Include="Images\add-group.png" />
    <Resource Include="Images\add-user.png" />
    <Resource Include="Images\book.png" />
    <Resource Include="Images\BOSCH2.jpg" />
    <Resource Include="Images\Bosch_Anker-Transparent.png" />
    <Resource Include="Images\Bosch_Anker.jpg" />
    <Resource Include="Images\Bosch_Anker48.png" />
    <Resource Include="Images\check128.png" />
    <Resource Include="Images\check32.png" />
    <Resource Include="Images\CircleFull128.png" />
    <Resource Include="Images\CircleFull32.png" />
    <Resource Include="Images\CircleRound128.png" />
    <Resource Include="Images\CircleRound32.png" />
    <Resource Include="Images\collapse.png" />
    <Resource Include="Images\copy.png" />
    <Resource Include="Images\copy16.png" />
    <Resource Include="Images\cut-content-button.png" />
    <Resource Include="Images\Database32.png" />
    <Resource Include="Images\Database64.png" />
    <Resource Include="Images\DB_Y.png" />
    <Resource Include="Images\DB_Y32.png" />
    <Resource Include="Images\delete.jpg" />
    <Resource Include="Images\drill.png" />
    <Resource Include="Images\edit.png" />
    <Resource Include="Images\eraser.png" />
    <Resource Include="Images\files-and-folders.png" />
    <Resource Include="Images\format_text_bold.png" />
    <Resource Include="Images\format_text_italic.png" />
    <Resource Include="Images\format_text_underline.png" />
    <Resource Include="Images\group.png" />
    <Resource Include="Images\hide.png" />
    <Resource Include="Images\left32.png" />
    <Resource Include="Images\machine-color.png" />
    <Resource Include="Images\machine.png" />
    <Resource Include="Images\man.png" />
    <Resource Include="Images\milling-machine.png" />
    <Resource Include="Images\minus128.png" />
    <Resource Include="Images\minus32.png" />
    <Resource Include="Images\multiply-1.png" />
    <Resource Include="Images\OrangeCross32.png" />
    <Resource Include="Images\parking.png" />
    <Resource Include="Images\paste-from-clipboard.png" />
    <Resource Include="Images\paste.png" />
    <Resource Include="Images\paste16.png" />
    <Resource Include="Images\plan-edit.png" />
    <Resource Include="Images\plan.png" />
    <Resource Include="Images\planning.png" />
    <Resource Include="Images\plus128.png" />
    <Resource Include="Images\plus32.png" />
    <Resource Include="Images\print.png" />
    <Resource Include="Images\print1.png" />
    <Resource Include="Images\refresh.png" />
    <Resource Include="Images\right32.png" />
    <Resource Include="Images\sort(2).png" />
    <Resource Include="Images\sort-by-attributes-Asc16 (2).png" />
    <Resource Include="Images\sort-by-attributes-Asc16.png" />
    <Resource Include="Images\sort-by-attributes-Desc16 (2).png" />
    <Resource Include="Images\sort-by-attributes-Desc16.png" />
    <Resource Include="Images\sort-by-attributes-interface-button-option.png" />
    <Resource Include="Images\sort-by-attributes.png" />
    <Resource Include="Images\spacing.png" />
    <Resource Include="Images\TooltipEmpl.png" />
    <Resource Include="Images\unknown-file.png" />
    <Resource Include="Images\user-edit.png" />
    <Resource Include="Images\user-profiles (1).png" />
    <Resource Include="Images\user-profiles.png" />
    <Resource Include="Images\waste.jpg" />
    <Resource Include="Images\waste2.jpg" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Images\SplashPic.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Themes\Light.Accent2.xaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Page>
    <Page Update="UserControls\Home.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
    <Page Update="UserControls\WorkerUserControl.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>
<!---->	
	<PropertyGroup>
		<Authors>Michael Schatzl (SCM2HL)</Authors>
		<AssemblyName>Lieferliste-WPF</AssemblyName>
		<Deterministic>false</Deterministic>   
		<Description>Feinplanung, Auftragsübersicht, Produkte</Description>
		<Title>Lieferliste-WPF</Title>
		<Company>Bosch-HlP/TEF2</Company>
		<DelaySign>True</DelaySign>
		<AssemblyVersion>1.0.*</AssemblyVersion>
		<FileVersion>1.0.*</FileVersion>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<EnableNETAnalyzers>False</EnableNETAnalyzers>
		<AnalysisLevel>5.0</AnalysisLevel>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<UserSecretsId>89393e76-c4e9-423b-a875-988090c78343</UserSecretsId>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
	</PropertyGroup>
  
  <!--<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v17.0\TextTemplating\Microsoft.TextTemplating.targets" />-->
  
</Project>
