<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CompositeCommands.Core\CompositeCommands.Core.csproj" />
    <ProjectReference Include="..\El2Utilities\El2Core.csproj" />
    <ProjectReference Include="..\ModuleShift\ModuleShift.csproj" />
    <ProjectReference Include="..\WpfCustomControlLibrary\WpfCustomControlLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="gong-wpf-dragdrop" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MahApps.Metro.IconPacks" />
    <PackageReference Include="MaterialDesignThemes.MahApps" />
    <PackageReference Include="Prism.Unity" />
    <PackageReference Include="System.Private.Uri" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Dialogs\InputStoppage.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Dialogs\CorrectionDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Dialogs\HistoryDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UserControls\MachineUserControl.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

</Project>
